# Generated by Django 6.0.1 on 2026-02-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'usersStudy',
                'ordering': ('-email',),
            },
        ),
    ]
