# Generated by Django 6.0.1 on 2026-02-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archivo',
            field=models.ForeignKey(blank=True, help_text='opcional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuariosStudyBro.archivomodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Campo Obligatorio', max_length=100, unique=True),
        ),
    ]
