# Generated by Django 6.0.1 on 2026-02-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0003_user_archivo_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivomodel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='usuariosStudyBro.user'),
        ),
    ]
