# Generated by Django 6.0.1 on 2026-02-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0004_remove_user_archivo_archivomodel_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserStudy',
        ),
    ]
