# Generated by Django 6.0.1 on 2026-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0005_rename_user_userstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivomodel',
            name='idTarjeta',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='archivomodel',
            name='url',
            field=models.FileField(upload_to='archivos/'),
        ),
    ]
