# Generated by Django 6.0.1 on 2026-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0006_archivomodel_idtarjeta_alter_archivomodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivomodel',
            name='idTarjeta',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
