# Generated by Django 6.0.1 on 2026-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0007_alter_archivomodel_idtarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivomodel',
            name='email',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
