# Generated by Django 6.0.1 on 2026-02-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0008_archivomodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivomodel',
            name='email',
        ),
    ]
