# Generated by Django 6.0.1 on 2026-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0009_remove_archivomodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivomodel',
            name='idTarjeta',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
