# Generated by Django 6.0.1 on 2026-02-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosStudyBro', '0010_alter_archivomodel_idtarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivomodel',
            name='idTarjeta',
        ),
        migrations.AddField(
            model_name='archivomodel',
            name='nombreTarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
